using AdvancedGSTApp.Data;
using AdvancedGSTApp.Models;
using AdvancedGSTApp.Services.Interfaces;
using Microsoft.EntityFrameworkCore;
using System.Text;

namespace AdvancedGSTApp.Services;

public class GstReportService(ApplicationDbContext db) : IGstReportService
{
    public async Task<DashboardViewModel> GetDashboardAsync() => new()
    {
        TotalSalesAmount = await db.SalesInvoices.SumAsync(x => x.GrandTotal), TotalPurchaseAmount = await db.PurchaseInvoices.SumAsync(x => x.GrandTotal),
        TotalInputTaxCredit = await db.InputTaxCreditLedgers.SumAsync(x => x.CGSTCredit + x.SGSTCredit + x.IGSTCredit),
        TotalCustomers = await db.Customers.CountAsync(), TotalSuppliers = await db.Suppliers.CountAsync(), PendingGstReturns = await db.GstReturnFilings.CountAsync(x => x.FilingStatus != "Filed"),
        RecentSalesInvoices = await db.SalesInvoices.Include(x => x.Customer).OrderByDescending(x => x.InvoiceDate).Take(5).ToListAsync(),
        RecentPurchaseInvoices = await db.PurchaseInvoices.Include(x => x.Supplier).OrderByDescending(x => x.InvoiceDate).Take(5).ToListAsync(),
        EInvoiceStatusSummary = await db.SalesInvoices.GroupBy(x => x.EInvoiceStatus).ToDictionaryAsync(x => x.Key, x => x.Count()), EWayBillStatusSummary = await db.SalesInvoices.GroupBy(x => x.EWayBillStatus).ToDictionaryAsync(x => x.Key, x => x.Count())
    };
    public async Task<GstPayableSummaryViewModel> GetGstPayableSummaryAsync(DateTime? from, DateTime? to)
    {
        var sales = db.SalesInvoices.AsQueryable(); var purchases = db.PurchaseInvoices.AsQueryable(); if (from.HasValue) { sales = sales.Where(x => x.InvoiceDate >= from); purchases = purchases.Where(x => x.InvoiceDate >= from); } if (to.HasValue) { sales = sales.Where(x => x.InvoiceDate <= to); purchases = purchases.Where(x => x.InvoiceDate <= to); }
        return new GstPayableSummaryViewModel { OutputCGST = await sales.SumAsync(x => x.CGSTAmount), OutputSGST = await sales.SumAsync(x => x.SGSTAmount), OutputIGST = await sales.SumAsync(x => x.IGSTAmount), InputCGST = await purchases.SumAsync(x => x.CGSTAmount), InputSGST = await purchases.SumAsync(x => x.SGSTAmount), InputIGST = await purchases.SumAsync(x => x.IGSTAmount) };
    }
    public async Task<List<Gstr1RowViewModel>> GetGstr1Async(int? month, string? financialYear) => await db.SalesInvoices.Include(x => x.Customer).Where(x => !month.HasValue || x.InvoiceDate.Month == month).Select(x => new Gstr1RowViewModel { InvoiceNumber = x.InvoiceNumber, InvoiceDate = x.InvoiceDate, CustomerGSTIN = x.Customer!.GSTIN, CustomerName = x.Customer.CustomerName, PlaceOfSupply = x.PlaceOfSupply, TaxableAmount = x.TaxableAmount, GSTRate = x.Items.Select(i => i.GSTPercentage).FirstOrDefault(), CGST = x.CGSTAmount, SGST = x.SGSTAmount, IGST = x.IGSTAmount, InvoiceTotal = x.GrandTotal, EInvoiceStatus = x.EInvoiceStatus, IRNNumber = x.IRNNumber }).ToListAsync();
    public async Task<Gstr3BViewModel> GetGstr3BAsync(int? month, string? financialYear) { var s = await GetGstPayableSummaryAsync(null, null); return new Gstr3BViewModel { OutputCGST = s.OutputCGST, OutputSGST = s.OutputSGST, OutputIGST = s.OutputIGST, InputCGST = s.InputCGST, InputSGST = s.InputSGST, InputIGST = s.InputIGST, EligibleITC = s.InputCGST + s.InputSGST + s.InputIGST, NetTaxPayable = s.TotalGstPayable, OutwardTaxableSupplies = await db.SalesInvoices.SumAsync(x => x.TaxableAmount) }; }
}
public class GstReturnService(ApplicationDbContext db, IGstReportService reports, IGstApiService api) : IGstReturnService
{ public async Task<GstReturnFiling> PrepareAsync(string type, int month, string fy) { var sum = await reports.GetGstPayableSummaryAsync(null, null); var filing = new GstReturnFiling { ReturnType = type, PeriodMonth = month, FinancialYear = fy, CGSTAmount = sum.OutputCGST, SGSTAmount = sum.OutputSGST, IGSTAmount = sum.OutputIGST, TotalTaxAmount = sum.OutputCGST + sum.OutputSGST + sum.OutputIGST, FilingStatus = "Prepared" }; db.GstReturnFilings.Add(filing); await db.SaveChangesAsync(); return filing; } public async Task<GstApiResult> SubmitAsync(int id) { var f = await db.GstReturnFilings.FindAsync(id) ?? throw new InvalidOperationException("Return filing not found"); var r = f.ReturnType == "GSTR-3B" ? await api.SubmitGstr3BAsync(id) : await api.SubmitGstr1Async(id); f.FilingStatus = r.Success ? "Filed" : "Failed"; f.FiledDate = r.Success ? DateTime.UtcNow : null; f.AcknowledgementNumber = r.ReferenceNumber; f.ErrorMessage = r.Success ? null : r.Message; f.ApiResponse = r.Payload; await db.SaveChangesAsync(); return r; } }
public class GstChallanService(ApplicationDbContext db, IGstApiService api) : IGstChallanService { public async Task<GstChallan> SaveAsync(GstChallan c) { c.TotalAmount = c.CGSTAmount + c.SGSTAmount + c.IGSTAmount + c.Interest + c.Penalty + c.LateFee; if (c.Id == 0) db.GstChallans.Add(c); else db.GstChallans.Update(c); await db.SaveChangesAsync(); return c; } public async Task<GstApiResult> GenerateAsync(int id) { var r = await api.GenerateGstChallanAsync(id); var c = await db.GstChallans.FindAsync(id); if (c != null) { c.ChallanNumber = r.ReferenceNumber ?? c.ChallanNumber; c.PaymentStatus = r.Success ? "Generated" : "Failed"; await db.SaveChangesAsync(); } return r; } }
public class GstReconciliationService(ApplicationDbContext db) : IGstReconciliationService { public async Task<GstReconciliation> ImportAsync(Stream stream, string fileName, string type, string period) { var rec = new GstReconciliation { Type = type, Period = period, UploadFilePath = fileName, Status = "Imported" }; db.GstReconciliations.Add(rec); await db.SaveChangesAsync(); return rec; } public async Task<List<GstReconciliationItem>> MatchAsync(int id) { var items = await db.GstReconciliationItems.Where(x => x.GstReconciliationId == id).ToListAsync(); var purchases = await db.PurchaseInvoices.Include(x => x.Supplier).ToListAsync(); foreach (var item in items) item.MatchStatus = purchases.Any(p => p.Supplier!.GSTIN == item.SupplierGSTIN && p.SupplierInvoiceNumber == item.InvoiceNumber && p.InvoiceDate.Date == item.InvoiceDate.Date && p.GrandTotal == item.InvoiceAmount) ? "Matched" : "Mismatched"; await db.SaveChangesAsync(); return items; } }
public class PdfService(ApplicationDbContext db) : IPdfService { public async Task<byte[]> GenerateInvoicePdfAsync(int id) { var inv = await db.SalesInvoices.Include(x => x.Customer).Include(x => x.Items).FirstAsync(x => x.Id == id); var html = $"GST Invoice {inv.InvoiceNumber}\nCustomer: {inv.Customer?.CustomerName}\nGrand Total: {inv.GrandTotal:N2}\nIRN: {inv.IRNNumber}\nEWB: {inv.EWayBillNumber}"; return Encoding.UTF8.GetBytes(html); } }
public class EmailService(IPdfService pdf) : IEmailService { public async Task SendInvoiceAsync(int salesInvoiceId, string toEmail) { _ = await pdf.GenerateInvoicePdfAsync(salesInvoiceId); /* SMTP placeholder reads appsettings; intentionally does not hardcode credentials. */ } }
public class AuditLogService(ApplicationDbContext db) : IAuditLogService { public async Task LogAsync(string actionType, string entityName, string entityId, object? oldValue, object? newValue) { db.AuditLogs.Add(new AuditLog { ActionType = actionType, EntityName = entityName, EntityId = entityId, OldValue = oldValue?.ToString(), NewValue = newValue?.ToString() }); await db.SaveChangesAsync(); } }
